package jorus.util;

import java.io.Serializable;

public class RGB24Image implements Serializable, ConvertableImage {

    // Generated by eclipse
    private static final long serialVersionUID = -5136719712051715163L;

    public final int width;

    public final int height;

    public final byte[] pixels;

    public RGB24Image(int width, int height) {
        this.width = width;
        this.height = height;
        pixels = new byte[width * height * 3];
    }

    public RGB24Image(int width, int height, byte[] image) {
        this.width = width;
        this.height = height;
        this.pixels = image;
    }

    public String toString() {
        return "RGB24Image [" + width + " x " + height + "], pixels.length = "
                + (pixels == null ? "null" : pixels.length);
    }

    public RGB24Image toRGB24() {
        return this;
    }
}
